version: "3.9"

services:
  ollama:
    build: ./ollama
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/local_models:/root/.ollama/models

  fastapi:
    build: ./fastapi
    container_name: fastapi_service
    ports:
      - "5050:5050"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama